#!/usr/bin/env bash

set -Eeuo pipefail

readlinkf() { perl -MCwd -MFile::Glob -l -e 'print Cwd::abs_path File::Glob::bsd_glob shift' "$1"; }
basedir=$(dirname "$(readlinkf "$0")")
script=$(basename "${BASH_SOURCE[${#BASH_SOURCE[@]}-1]}")

if [[ ! $(command -v zip) ]]; then
    echo "zip command not found" 1>&2
    exit 1
fi

cd "${basedir}"
mkdir .GitSync.spoon
cd .GitSync.spoon
cp -R ../* .
cd ..
mv .GitSync.spoon GitSync.spoon
zip -9 --exclude "GitSync.spoon/make-package" -r GitSync.spoon.zip GitSync.spoon
rm -rf GitSync.spoon

echo ""
echo "- bump the version number in init.lua in obj.version AND Download header"
echo "- upload the zip file to GitHub releases area"
echo "- update git-sync-spoon.wiki/version.txt"
